### ISSUE TITLE
Sort alphabetically, keep symbols first

### ISSUE THREAD

**Issue by moshe** [KyleMayes/eslint-plugin-ordered-imports#11]
Hi @KyleMayes 👋 Great project!
I working on a project that uses lodash and imports it as an underscore symbol (`_`).
The thing is that NodeJs default sort symbols between lower case and upper case groups.
```
> ["a", "c", "b", "A", "_"].sort()
[ 'A', '_', 'a', 'b', 'c' ]
```
There is a chance that I can make `eslint-plugin-ordered-imports` to sort and keep the lodash import first?
I tried creating two groups with the same priority and two groups with the same name but different priority without success

Actual:
```
import PropTypes from 'prop-types';
import React from 'react';
import _ from 'lodash';
```

Expected:
```
import _ from 'lodash';
import PropTypes from 'prop-types';
import React from 'react';
```

Thanks!

**Comment by KyleMayes** [comment]
I made this the default behavior starting in the newly released `v0.4.0`.
