### ISSUE TITLE
In 'group-ordering', `order: 5` is treated as greater than `order: 10`

### ISSUE THREAD

**Issue by earshinov** [KyleMayes/eslint-plugin-ordered-imports#16]
...because of `.toString()` here: https://github.com/KyleMayes/eslint-plugin-ordered-imports/blob/b4a3488a2a906fa4c2b2656e8302ffee2f7e0860/src/rule.ts#L61

Please let me know if you need repro or something.

Spent an hour digging this up.

`rule.spec.ts` only checks two-digit order values.

_Edit_: wording.

**Comment by KyleMayes** [comment]
Fixed in `v0.5.0`.
